# Generated by Django 4.1.7 on 2023-03-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('adres', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=200)),
                ('advance', models.CharField(max_length=200)),
                ('roomtype', models.CharField(max_length=200)),
                ('roomno', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'IPInfo_tbl',
            },
        ),
    ]
