# Generated by Django 4.1.7 on 2023-03-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipmodel',
            name='admitdate',
            field=models.CharField(default='some_value', max_length=200),
        ),
        migrations.AddField(
            model_name='ipmodel',
            name='dischargedate',
            field=models.CharField(default='some_value', max_length=200),
        ),
        migrations.AddField(
            model_name='ipmodel',
            name='doctorname',
            field=models.CharField(default='some_value', max_length=200),
        ),
        migrations.AddField(
            model_name='ipmodel',
            name='ipno',
            field=models.CharField(default='some_value', max_length=200),
        ),
        migrations.AddField(
            model_name='ipmodel',
            name='perid',
            field=models.CharField(default='some_value', max_length=200),
        ),
    ]
